from typing import *
class BaseDatabase:
    def __init__(self): ...
    def set_value(self, key: Hashable, val: Any) -> bool: ...
    def get_value(self, key: Hashable) -> Any: ...
    def delete_value(self, key: Hashable) -> Any: ...
